# Basics
## Concepts
- multidimensional array of the same type
- NumPy’s array class is called ndarray

## Attributes of ndarray
- .ndim
- .shape
- .size
- .dtype

## Array creation
- from list or tuple

In [2]:
import numpy as np
a = np.array(((1,2,3), (4,5,6)))
a

array([[1, 2, 3],
       [4, 5, 6]])

- create a placeholder
    - np.zeros
    - np.ones
    - np.empty
        - creates an array whose initial content is random 

In [5]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

- create sequences of numbers
    - np.arange(start, end, step)
        - similar with range, but returns an array
        -  not possible to predict the number of elements obtained
    - np.linspace(start, end, numelements)

In [7]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [12]:
np.linspace(0, 10, 9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

## Basic operations