# Basics
## Concepts
- multidimensional array of the same type
- NumPy’s array class is called ndarray

## Attributes of ndarray
- .ndim
- .shape
- .size
- .dtype

## Array creation
- from list or tuple

In [2]:
import numpy as np
a = np.array(((1,2,3), (4,5,6)))
a

array([[1, 2, 3],
       [4, 5, 6]])

- create a placeholder
    - np.zeros
    - np.ones
    - np.empty
        - creates an array whose initial content is random 

In [5]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

- create sequences of numbers
    - np.arange(start, end, step)
        - similar with range, but returns an array
        -  not possible to predict the number of elements obtained
    - np.linspace(start, end, numelements)

In [7]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [12]:
np.linspace(0, 10, 9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

## Basic operations

- elementwise product: A * B

- matrix product: A.dot(B)
    
- ndarray class methods

In [17]:
A = np.random.random_sample((2,3))
A

array([[0.39192556, 0.86632858, 0.04322315],
       [0.50506182, 0.49898504, 0.54918441]])

In [18]:
A.sum()

2.85470856840591

In [19]:
A.max()

0.8663285814378455

In [20]:
A.sum(axis=0)

array([0.89698738, 1.36531363, 0.59240756])

In [21]:
A.cumsum(axis=1)

array([[0.39192556, 1.25825414, 1.3014773 ],
       [0.50506182, 1.00404687, 1.55323127]])

- universal functions
    - amiliar mathematical functions such as sin, cos, and exp
    - np.exp()

## Indexing, Slicing and Iterating

- similar with list
- dots (...) represent as many colons as needed to produce a complete indexing tuple
    - [1,2,...] is equivalent to x[1,2,:,:,:]
- np.flat: iterte over all the elements

## Shpae manipulation

In [26]:
a = np.array(((1,2,3), (4,5,6)))
a = a.ravel() # returns the array, flattened
a

array([1, 2, 3, 4, 5, 6])

In [27]:
a.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
a.shape

(6,)

In [30]:
a.resize((2,3))
a.shape

(2, 3)